src/Entity/Productos.php
<?php

namespace App\Entity;

use App\Repository\ProductosRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductosRepository::class)]
class Productos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $marca = null;

    #[ORM\Column(length: 255)]
    private ?string $descripcion = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $formato = null;

    #[ORM\Column(nullable: true)]
    private ?float $precio_A = null;

    #[ORM\Column(nullable: true)]
    private ?float $precio_C = null;

    #[ORM\Column(nullable: true)]
    private ?float $precio_D = null;

    #[ORM\Column(length: 255, nullable: true)]
    public ?string $Imagen_url = null;

    #[ORM\Column(length: 70)]
    private ?string $Supermercado = null;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getMarca(): ?string
    {
        return $this->marca;
    }

    public function setMarca(string $marca): self
    {
        $this->marca = $marca;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getFormato(): ?string
    {
        return $this->formato;
    }

    public function setFormato(?string $formato): self
    {
        $this->formato = $formato;

        return $this;
    }

    public function getPrecioA(): ?float
    {
        return $this->precio_A;
    }

    public function setPrecioA(?float $precio_A): self
    {
        $this->precio_A = $precio_A;

        return $this;
    }

    public function getPrecioC(): ?float
    {
        return $this->precio_C;
    }

    public function setPrecioC(?float $precio_C): self
    {
        $this->precio_C = $precio_C;

        return $this;
    }

    public function getPrecioD(): ?float
    {
        return $this->precio_D;
    }

    public function setPrecioD(?float $precio_D): self
    {
        $this->precio_D = $precio_D;

        return $this;
    }

    public function getImagenUrl(): ?string
    {
        return $this->Imagen_url;
    }

    public function setImagenUrl(?string $Imagen_url): self
    {
        $this->Imagen_url = $Imagen_url;

        return $this;
    }

    public function getSupermercado(): ?string
    {
        return $this->Supermercado;
    }

    public function setSupermercado(string $Supermercado): self
    {
        $this->Supermercado = $Supermercado;

        return $this;
    }

    
   
}

src/Form/ProductosType.php
<?php

namespace App\Form;

use App\Entity\Productos;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nombre')
            ->add('marca')
            ->add('descripcion')
            ->add('formato')
            ->add('precio_A')
            ->add('precio_C')
            ->add('precio_D')
            ->add('Supermercado')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Productos::class,
        ]);
    }
}

src/Controller/ProductoController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductoController extends AbstractController
{
    #[Route('/producto', name: 'app_producto')]
    public function index(): Response
    {
        return $this->render('producto/index.html.twig', [
            'controller_name' => 'ProductoController',
        ]);
    }
}

src/Controller/ProductosController.php
<?php

namespace App\Controller;

use App\Entity\Productos;
use App\Form\ProductosType;
use App\Repository\ProductosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/productos')]
class ProductosController extends AbstractController
{
    private $em;
    /**
     * @param $em
     */
    public function __construct(EntityManagerInterface $em){
        $this->em=$em;
    }
    

    #[Route('/buscar', name: 'app_productos_buscar', methods: ['GET'])]
    public function buscar(Request $request, ProductosRepository $productosRepository): Response
    {
        $query = $request->query->get('q'); // Obtener el término de búsqueda de la URL
        $productos = $productosRepository->buscarPorNombre($query);
    
        return $this->render('productos/search.html.twig', [
            'productos' => $productos,
        ]);
    }
    
    #[Route('/', name: 'app_productos_index', methods: ['GET'])]
    public function indexs(Request $request, ProductosRepository $productosRepository, PaginatorInterface $paginator): Response
    {   
        $query = $productosRepository->createQueryBuilder('p')->getQuery();
        $pagination = $paginator->paginate($query, $request->query->getInt('page', 1), 10);

        return $this->render('productos/index.html.twig', [
            'productos' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app_productos_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProductosRepository $productosRepository): Response
    {
        $producto = new Productos();
        $form = $this->createForm(ProductosType::class, $producto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productosRepository->save($producto, true);

            return $this->redirectToRoute('app_productos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('productos/new.html.twig', [
            'producto' => $producto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_productos_show', methods: ['GET'])]
    public function show(Productos $producto): Response
    {
        return $this->render('productos/show.html.twig', [
            'producto' => $producto,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_productos_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Productos $producto, ProductosRepository $productosRepository): Response
    {
        $form = $this->createForm(ProductosType::class, $producto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productosRepository->save($producto, true);

            return $this->redirectToRoute('app_productos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('productos/edit.html.twig', [
            'producto' => $producto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_productos_delete', methods: ['POST'])]
    public function delete(Request $request, Productos $producto, ProductosRepository $productosRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$producto->getId(), $request->request->get('_token'))) {
            $productosRepository->remove($producto, true);
        }

        return $this->redirectToRoute('app_productos_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/productos/_delete_form.html.twig
<form method="post" action="{{ path('app_productos_delete', {'id': producto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ producto.id) }}">
    <button class="btn">Delete</button>
</form>

templates/productos/_form.html.twig
{{ form_start(form) }}
{# {% dump variable %} #}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/productos/_productos.html.twig
{% for producto in productos %}
    <div class="col-sm-3">
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ producto.nombre }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ producto.Supermercado }}</h6>
                <img src="{{ asset(producto.Imagen_url) }}" alt="Imagen de {{ producto.nombre }}" style="max-width: 100%; height: 200px; object-fit: cover;">
                <p class="card-text">{{ producto.descripcion }}</p>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ producto.precioA }} € {{ producto.formato }}</li>
                    <li class="list-group-item">{{ producto.marca }}</li>
                </ul>
            </div>
        </div>
    </div>
{% else %}
    <h1 colspan="10">No se encontraron resultados</h1>
{% endfor %}

templates/productos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Productos{% endblock %}

{% block body %}
    <h1>Edit Productos</h1>

    {{ include('productos/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_productos_index') }}">back to list</a>

    {{ include('productos/_delete_form.html.twig') }}
{% endblock %}

templates/productos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Productos index{% endblock %}

{% block body %}


    <div class="container">
        <h1 class="mb-5">Productos index</h1>
        <form action="{{ path('app_productos_buscar') }}" method="GET" class="mb-4">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Buscar productos">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Buscar</button>
                </div>
            </div>
        </form>
        
            <div class="row">
                {% for producto in productos %}
                    <div class="col-sm-3">
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">{{ producto.nombre }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ producto.Supermercado }}</h6>
                                <img src="{{ asset(producto.Imagen_url) }}" alt="Imagen de {{ producto.nombre }}" style="max-width: 100%; height: 200px; object-fit: cover;">
                                <p class="card-text">{{ producto.descripcion }}</p>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">{{ producto.precioA }} € {{ producto.formato }}</li>
                                    <li class="list-group-item">{{ producto.marca }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <h1 colspan="10">no records found</h1>
                {% endfor %}
            </div>
                
                <div class="pagination">
                    {{ knp_pagination_render(productos) }}
                </div>
        
    </div>

<a href="{{ path('app_productos_new') }}">Create new</a>

    <a href="{{ path('app_productos_new') }}">Create new</a>
{% endblock %}

templates/productos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Productos{% endblock %}

{% block body %}
    <h1>Create new Productos</h1>

    {{ include('productos/_form.html.twig') }}

    <a href="{{ path('app_productos_index') }}">back to list</a>
{% endblock %}

templates/productos/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Productos index{% endblock %}

{% block body %}
<div class="container">
    <h1 class="mb-5">Resultados de búsqueda</h1>
    
    <div class="row">
        {% for producto in productos %}
            <div class="col-sm-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ producto.nombre }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ producto.Supermercado }}</h6>
                        <img src="{{ asset(producto.Imagen_url) }}" alt="Imagen de {{ producto.nombre }}" style="max-width: 100%; height: 200px; object-fit: cover;">
                        <p class="card-text">{{ producto.descripcion }}</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ producto.precioA }} € {{ producto.formato }}</li>
                            <li class="list-group-item">{{ producto.marca }}</li>
                        </ul>
                    </div><!-- Código para mostrar los detalles del producto -->
                </div>
            </div>
        {% else %}
            <h1 colspan="10">No se encontraron resultados</h1>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/productos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Productos{% endblock %}

{% block body %}
    <h1>Productos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ producto.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ producto.nombre }}</td>
            </tr>
            <tr>
                <th>Marca</th>
                <td>{{ producto.marca }}</td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ producto.descripcion }}</td>
            </tr>
            <tr>
                <th>Formato</th>
                <td>{{ producto.formato }}</td>
            </tr>
            <tr>
                <th>Precio_a</th>
                <td>{{ producto.precioA }}</td>
            </tr>
            <tr>
                <th>Precio_b</th>
                <td>{{ producto.precioB }}</td>
            </tr>
            <tr>
                <th>Precio_c</th>
                <td>{{ producto.precioC }}</td>
            </tr>
            <tr>
                <th>Precio_d</th>
                <td>{{ producto.precioD }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_productos_index') }}">back to list</a>

    <a href="{{ path('app_productos_edit', {'id': producto.id}) }}">edit</a>

    {{ include('productos/_delete_form.html.twig') }}
{% endblock %}